version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-new_project
        container_name: laravel-new_project-app
        restart: unless-stopped
        working_dir: /var/www/new_project
        volumes:
            - .:/var/www/new_project
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - mynetwork

    webserver:
        image: nginx:alpine
        container_name: laravel-new_project-webserver
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/new_project
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - mynetwork
        depends_on:
            - app

    db:
        image: mysql:5.7
        container_name: laravel-new_project-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - mynetwork

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-new_project-phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - db
        networks:
            - mynetwork

networks:
    mynetwork:
        external: true
        driver: bridge

volumes:
    dbdata:
